### ISSUE TITLE
Demo Using Mybinder

### ISSUE THREAD

**Issue by psychemedia** [cirlabs/miditime#14]
This package can be demoed inside a Jupyter notebook using [MyBinder](https://mybinder.org/) if something like the `music21` package (for example), is also installed into the environment in order to play back the created midi file.

An minimal example is then something like:

```python
from miditime.miditime import MIDITime

# Instantiate the class with a tempo (120bpm is the default) and an output file destination.
mymidi = MIDITime(120, 'myfile.mid')

# Create a list of notes. Each note is a list: [time, pitch, velocity, duration]
midinotes = [
    [0, 60, 127, 3], 
    [1, 61, 127, 4], 
    [2, 61, 127, 6]]

# Add a track with those notes
mymidi.add_track(midinotes)

# Output the .mid file
mymidi.save_midi() #saves to myfile.mid by default
```

And then play back with:

```python
from music21 import converter
m = converter.parse('myfile.mid')
m.show('midi')
```

**Comment by mikejcorey** [comment]
I know this contribution is from a long time ago, but thank you so much! I always wanted a better way to play this back without using a command-line or gui converter. I'll add this an example.

**Comment by psychemedia** [comment]
This may also work in JupyterLite, the purely in-browser Jupyter environment.
