### ISSUE TITLE
Adding MIDI channels to a note

### ISSUE THREAD

**Issue by ledm** [cirlabs/miditime#16]
At the moment, a MIDI note is specified by its pitch, duration, time, and velocity. Many VST's also include a channel, which impacts things like whether the note uses staccato or a sustained sample. Is there anyway to add a channel variable to MIDITime?

**Comment by Nia521** [comment]
HI, I do not currently know the answer - sorry! I am just glad to see that there is someone else out there that is just as interested in this particular topic as me. I'm really just barely dusting off my old coding skill.  Maybe someday I will have answers.

**Comment by ledm** [comment]
Hi, I've found a solution. This package is basically a wrapper for the midiutils package: https://github.com/sole/MIDIUtils

So, I've started using that package which has a finer control of the midi notes, including stuff like changing tempo, channels, etc.  However, I did make the first 7 pieces in this playlist using miditime: https://www.youtube.com/playlist?list=PL27v682n8E2Sla8U7jJph9w9M6nYln-W3

**Comment by Nia521** [comment]
Hey, thanks for the links. What a great way to start my day. The World
Ocean Day Quintet was amazing, but Giant Steps Spin Up was the one the was
almost radio ready😄. Do you have the raw data online?

**Comment by ledm** [comment]
Thanks! It's good fun to play around with data like this.

In terms of data availability.... Sort of... the raw data is available through CMIP6 (https://esgf-node.llnl.gov/search/cmip6/), which I processed into time series data using BGC-val, https://gmd.copernicus.org/articles/11/4215/2018/

The processed time series data is not available unfortunately. I'm hoping to publish the code at some point too, but it could be a while.

**Comment by Nia521** [comment]
Cool beans. Maybe one day we could collaborate on a project I've been
working on. I think you will seriously enjoy it. Until then, thanks for the
good work!

-best

**Comment by mikejcorey** [comment]
Hi all: I know this is an old ticket, but with the latest updates you can now change programs/instruments.
