### ISSUE TITLE
setuptools-markdown is deprecated

### ISSUE THREAD

**Issue by jgarte** [cirlabs/miditime#19]
This is a ticket to migrate away from `setuptools-markdown` since it is deprecated:

https://github.com/msabramo/setuptools-markdown?tab=readme-ov-file#this-project-is-deprecated

**Comment by mikejcorey** [comment]
Latest commits include a revamp of package to use hatch instead of setuptools, which also eliminates this dependency.

**Comment by jgarte** [comment]
That's great! Thanks for adding that. Much appreciated.
